# Generated by Django 4.1.1 on 2022-10-05 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='显示顺序')),
                ('menu_type', models.CharField(blank=True, default='D', max_length=1, null=True, verbose_name='菜单类型')),
                ('target', models.CharField(blank=True, default='menuItem', max_length=10, null=True, verbose_name='打开方式')),
                ('visible', models.CharField(blank=True, default='1', max_length=1, null=True, verbose_name='是否隐藏')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='打开方式')),
                ('disc', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('url', models.CharField(max_length=128, unique=True)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mana.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('disc', models.CharField(max_length=50)),
                ('permissions', models.ManyToManyField(to='mana.permission')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('gender', models.CharField(default='0', max_length=1)),
                ('nickname', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('permissions', models.ManyToManyField(blank=True, to='mana.permission')),
                ('roles', models.ManyToManyField(to='mana.role')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='create_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)s_related', to='mana.userinfo', to_field='username'),
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mana.menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(app_label)s_%(class)s_related', to='mana.userinfo', to_field='username'),
        ),
    ]
