# Generated by Django 3.2.16 on 2022-11-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mana', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
