# Generated by Django 3.2.16 on 2022-11-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mana', '0004_alter_userinfo_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
