# Generated by Django 3.2.16 on 2022-11-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mana', '0013_alter_permission_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_del',
            field=models.CharField(default='0', max_length=1, verbose_name='删除标记'),
        ),
    ]
