# Generated by Django 4.1.2 on 2022-11-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mana', '0015_user2genealogy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user2genealogy',
            old_name='is_public',
            new_name='is_create',
        ),
    ]
