# Generated by Django 4.1.1 on 2022-10-05 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mana', '0002_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docformat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, unique=True, verbose_name='')),
                ('disc', models.CharField(max_length=50, verbose_name='')),
                ('order', models.CharField(max_length=2, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Doctype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, unique=True, verbose_name='')),
                ('disc', models.CharField(max_length=50, verbose_name='')),
                ('order', models.CharField(max_length=2, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Genealogy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='标题')),
                ('sername', models.CharField(max_length=10, verbose_name='姓氏')),
                ('hall_title', models.CharField(blank=True, max_length=10, verbose_name='堂号')),
                ('county_title', models.CharField(blank=True, max_length=10, verbose_name='郡望号')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='位置')),
                ('contact', models.CharField(blank=True, max_length=10, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=13, verbose_name='联系电话')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('is_public', models.CharField(default='0', max_length=32, verbose_name='是否公开')),
                ('access_pwd', models.CharField(blank=True, max_length=8, verbose_name='访问密码')),
                ('is_del', models.CharField(default='0', max_length=1, verbose_name='删除标记')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)s_related', to='mana.userinfo', to_field='username')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(app_label)s_%(class)s_related', to='mana.userinfo', to_field='username')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('surname', models.CharField(max_length=10, verbose_name='姓')),
                ('name', models.CharField(max_length=10, verbose_name='名')),
                ('zi', models.CharField(max_length=10, verbose_name='字')),
                ('hao', models.CharField(max_length=10, verbose_name='号')),
                ('common_name', models.CharField(max_length=10, verbose_name='常用名')),
                ('gender', models.CharField(default='0', max_length=1, verbose_name='性别')),
                ('ad_birth', models.DateTimeField(blank=True, null=True, verbose_name='公元出生日期')),
                ('ce_birth', models.CharField(max_length=32, verbose_name='年号出生日期')),
                ('birth_place', models.CharField(max_length=50, verbose_name='出生地')),
                ('ad_death', models.DateTimeField(blank=True, null=True, verbose_name='公元逝世日期')),
                ('ce_death', models.CharField(max_length=32, verbose_name='年号逝世日期')),
                ('death_place', models.CharField(max_length=50, verbose_name='逝世地')),
                ('line_name', models.CharField(max_length=2, verbose_name='家族排行')),
                ('generetion', models.CharField(max_length=2, verbose_name='世代数')),
                ('rank', models.CharField(max_length=32, verbose_name='出生排行')),
                ('is_alive', models.CharField(max_length=1, verbose_name='是否健在')),
                ('biography', models.CharField(max_length=1000, verbose_name='生平简介')),
                ('epitaph', models.CharField(max_length=1000, verbose_name='墓志铭')),
                ('idcard_no', models.CharField(max_length=18, unique=True, verbose_name='身份编号')),
                ('address', models.CharField(max_length=50, verbose_name='住址')),
                ('phone', models.CharField(max_length=11, verbose_name='电话号码')),
                ('idcard_type', models.CharField(default='居民身份证', max_length=32, verbose_name='身份证')),
                ('is_del', models.CharField(default='0', max_length=1, verbose_name='删除标记')),
                ('note', models.CharField(max_length=500, verbose_name='')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)s_related', to='mana.userinfo', to_field='username')),
                ('farther', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indi_farther', to='home.individual')),
                ('gene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indi_genealogy', to='home.genealogy', to_field='title')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indi_mother', to='home.individual')),
                ('spouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indi_spouse', to='home.individual')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(app_label)s_%(class)s_related', to='mana.userinfo', to_field='username')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50, verbose_name='')),
                ('path', models.CharField(max_length=50, verbose_name='')),
                ('is_del', models.CharField(default='0', max_length=1, verbose_name='删除标记')),
                ('Genealogy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.genealogy', to_field='title')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='')),
                ('author', models.CharField(max_length=10, verbose_name='')),
                ('content', models.CharField(max_length=5000, verbose_name='')),
                ('rank', models.CharField(max_length=500, verbose_name='')),
                ('is_del', models.CharField(default='0', max_length=1, verbose_name='删除标记')),
                ('visible', models.CharField(default='1', max_length=1, verbose_name='是否可见')),
                ('docformat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.docformat', to_field='title')),
                ('doctype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.doctype', to_field='title')),
                ('genealogy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.genealogy', to_field='title', verbose_name='')),
            ],
        ),
    ]
