# Generated by Django 4.1.2 on 2022-10-07 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_genealogy_update_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='gene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indi_genealogy', to='home.genealogy'),
        ),
    ]
