# Generated by Django 3.2.16 on 2022-10-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20221017_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='cemetery',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='葬地'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='住址'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='biography',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='生平简介'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='birth_place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='出生地'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='ce_birth',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='年号出生日期'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='ce_death',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='年号逝世日期'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='common_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='常用名'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='death_place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='逝世地'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='epitaph',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='墓志铭'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='generetion',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='世代数'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='hao',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='号'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='idcard_type',
            field=models.CharField(blank=True, default='居民身份证', max_length=32, null=True, verbose_name='身份证'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='is_alive',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='是否健在'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='line_name',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='家族排行'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='individual',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='rank',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='出生排行'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='zi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='字'),
        ),
    ]
