# Generated by Django 3.2.16 on 2022-10-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_document_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docformat',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name=''),
        ),
    ]
