# Generated by Django 3.2.16 on 2022-10-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_document_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='rank',
            field=models.IntegerField(verbose_name=''),
        ),
    ]
