# Generated by Django 4.1.2 on 2022-11-09 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_userip_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userip',
            name='last_visit',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最近一次访问'),
        ),
    ]
